import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
titanic_df = pd.read_csv('C:/Users/i/Desktop/python/datasets/test.csv')
print(titanic_df.head())
print(titanic_df.isnull().sum())
titanic_df['Age'].fillna(titanic_df['Age'].median(), inplace=True)
titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0], inplace=True)
titanic_df.drop(columns=['Cabin'], inplace=True)  
titanic_df['Sex'] = titanic_df['Sex'].map({'male': 0, 'female': 1})
print(titanic_df.describe())
plt.figure(figsize=(10, 6))
plt.hist(titanic_df['Age'], bins=30, color='skyblue', edgecolor='black')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.title('Age Distribution on the Titanic')
plt.show()
gender_counts = titanic_df['Sex'].value_counts()
plt.figure(figsize=(10, 6))
plt.bar(['Male', 'Female'], gender_counts.values, color=['blue', 'pink'])
plt.xlabel('Gender')
plt.ylabel('Frequency')
plt.title('Gender Distribution on the Titanic')
plt.show()
survived_counts = titanic_df['Survived'].value_counts()
plt.figure(figsize=(10, 6))
plt.bar(['Not Survived', 'Survived'], survived_counts.values, color=['red', 'green'])
plt.xlabel('Survival')
plt.ylabel('Frequency')
plt.title('Survival Distribution on the Titanic')
plt.show()
sns.pairplot(titanic_df[['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']])
plt.show()
numeric_df = titanic_df.select_dtypes(include=[float, int])
print(numeric_df.head())
corr_matrix = numeric_df.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()